---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: external-secrets-manager
  namespace: vault
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        spec:
          serviceAccountName: external-secrets-manager-serviceacc
          containers:
          - name: external-secrets-manager
            image: rahulk789/external-secrets-manager
            envFrom:
            - secretRef:
                name: external-secrets-manager-env
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-manager-env
  namespace: vault
type: Opaque
data:
  VAULT_ADDRESS: aHR0cDovLzEwLjQzLjQxLjk6ODIwMC8=
  VAULT_TOKEN: aHZzLlFqZEo4ZFhPV2hiQjFwb0lqeHU0MGpmdQ==
  CLUSTER_SECRET_STORE: dmF1bHQtYmFja2VuZA==
  ES_GIT_REPOSITORY: aHR0cHM6Ly9naXRodWIuY29tL3JhaHVsazc4OS9sb2NhbC1zZWNyZXRzLWV4YW1wbGU=
  GIT_USER: cmFodWxrNzg5
  GIT_EMAIL: cmFodWwudS5pbmRpYUBnbWFpbC5jb20=
  GIT_PASSWORD: Z2l0aHViX3BhdF8xMUFUNkVaN1EwbGloWUZyOXBMdGltXzdySXRlVEZXZ2xKeUp5NWxxbGprQXFHQzhabGdBZVRRN1ZIa2RpazNkWnpaRERISEVKQVlIUVlnRmRF
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: external-secrets-manager-clusterrolebinding
  namespace: vault
subjects:
- kind: ServiceAccount
  name: external-secrets-manager-serviceacc # Name is case sensitive
  namespace: vault
roleRef:
  kind: ClusterRole
  name: external-secrets-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-manager-serviceacc
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: external-secrets-manager-clusterrole
  resourceVersion: "77"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
