
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: one-secrets-es
  namespace: project-beta
spec:
  data: 
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hello-world/one-secrets
      property: hi
    secretKey: hi
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend 
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: one-secrets-secret