
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testing/-es
  namespace: project-beta
spec:
  data: 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: two-secrets-es
  namespace: project-beta
spec:
  data: 
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hello-world/two-secrets
      property: two-1
    secretKey: two-1
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hello-world/two-secrets
      property: two-2
    secretKey: two-2
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend 
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: two-secrets-secret