---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: three-secret-es
  namespace: project-beta
spec:
  data: 
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hello-world/three-secret
      property: asdasdasdsa
    secretKey: asdasdasdsa
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: hello-world/three-secret
      property: sadasdasd
    secretKey: sadasdasd
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault_backend 
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: three-secret-secret
---